-- Guarda cada linha da planilha original como uma combinação exata para o editor de treino.

CREATE TABLE IF NOT EXISTS public.exercise_combo_options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  muscle_group_id uuid REFERENCES public.muscle_groups(id) ON DELETE SET NULL,
  exercise_catalog_id uuid NOT NULL REFERENCES public.exercise_catalog(id) ON DELETE CASCADE,
  exercise_variation_id uuid NOT NULL REFERENCES public.exercise_variations(id) ON DELETE CASCADE,
  equipment_id uuid REFERENCES public.equipment_catalog(id) ON DELETE SET NULL,
  grip_footing_id uuid REFERENCES public.grip_footing_catalog(id) ON DELETE SET NULL,
  method_id uuid REFERENCES public.method_catalog(id) ON DELETE SET NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_exercise_combo_options_muscle_group
  ON public.exercise_combo_options(muscle_group_id);

CREATE INDEX IF NOT EXISTS idx_exercise_combo_options_catalog
  ON public.exercise_combo_options(exercise_catalog_id);

CREATE INDEX IF NOT EXISTS idx_exercise_combo_options_variation
  ON public.exercise_combo_options(exercise_variation_id);

CREATE INDEX IF NOT EXISTS idx_exercise_combo_options_equipment
  ON public.exercise_combo_options(equipment_id);

CREATE INDEX IF NOT EXISTS idx_exercise_combo_options_grip_footing
  ON public.exercise_combo_options(grip_footing_id);

CREATE INDEX IF NOT EXISTS idx_exercise_combo_options_method
  ON public.exercise_combo_options(method_id);

ALTER TABLE public.exercise_combo_options ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Personals read exercise combo options" ON public.exercise_combo_options;
CREATE POLICY "Personals read exercise combo options"
  ON public.exercise_combo_options FOR SELECT
  USING (auth.uid() IS NOT NULL);